### PR TITLE
added src/index.js for easier imports

### PR DESCRIPTION
**Pull request by teameh**

### CODE REVIEW

**Comment by chiel** [comment]
Nice, one thing - you don't need to put `/index` behind the import paths since the module lookup algorithm will automatically do this. :)

**Comment by teameh** [comment]
Yeah I know but I like the explicitness. Otherwise I might think `/utils` is a file instead of a directory when reading the import..

**Comment by chiel** [comment]
Fair enough! I did remove those paths though, but it's good to hear your point of view on them.

**Comment by teameh** [comment]
😫

**Pull request merged**
